name: testenv
channels:
  - conda-forge
dependencies:
  - libgdal-netcdf
  - python-build
  - gdal
  - geopandas
  - geos
  - netCDF4
  - numpy
  - pytest
  - pytest-cov
  - rasterio
  - rioxarray
  - xarray
  - twine
