#ifndef RASTER_OVERLAY_CPP_SEGMENT_ORIENTATION_H
#define RASTER_OVERLAY_CPP_SEGMENT_ORIENTATION_H

enum class SegmentOrientation {
    HORIZONTAL_RIGHT,
    HORIZONTAL_LEFT,
    VERTICAL_UP,
    VERTICAL_DOWN,
    ANGLED
};

#endif //RASTER_OVERLAY_CPP_SEGMENT_ORIENTATION_H
